BEGIN;
DELETE FROM data_property;
DELETE FROM data_datafile_property;
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (1, '_prop_dielectric_permittivity_relative_epsrij', '_dielectric_permittivity_relative_epsrij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (2, '_prop_dielectric_permittivity_relative_epsrijS', '_dielectric_permittivity_relative_epsrijS', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (3, '_prop_dielectric_permittivity_relative_epsrijT', '_dielectric_permittivity_relative_epsrijT', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (4, '_prop_dielectric_stiffness_relative_betrijS', '_dielectric_stiffness_relative_betrijS', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (5, '_prop_dielectric_stiffness_relative_betrijT', '_dielectric_stiffness_relative_betrijT', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (6, '_prop_elastic_TOEC_stiffness_cijk', '_elastic_TOEC_stiffness_cijk', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (7, '_prop_elastic_compliance_sij', '_elastic_compliance_sij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (8, '_prop_elastic_compliance_sijD', '_elastic_compliance_sijD', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (9, '_prop_elastic_compliance_sijE', '_elastic_compliance_sijE', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (10, '_prop_elastic_stiffness_cij', '_elastic_stiffness_cij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (11, '_prop_elastic_stiffness_cijD', '_elastic_stiffness_cijD', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (12, '_prop_elastic_stiffness_cijE', '_elastic_stiffness_cijE', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (13, '_prop_elastic_stiffness_cijS', '_elastic_stiffness_cijS', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (14, '_prop_electric_charge_carrier_concentration_n', '_electric_charge_carrier_concentration_n', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (15, '_prop_electric_coercive_field_Eci', '_electric_coercive_field_Eci', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (16, '_prop_electric_remnant_polarisation_Pri', '_electric_remnant_polarisation_Pri', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (17, '_prop_electric_resistivity_rhoeij', '_electric_resistivity_rhoeij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (18, '_prop_electromechanical_coupling_kij', '_electromechanical_coupling_kij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (19, '_prop_electrooptic_rijkS', '_electrooptic_rijkS', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (20, '_prop_electrooptic_rijkT', '_electrooptic_rijkT', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (21, '_prop_electrostriction_Dij', '_electrostriction_Dij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (22, '_prop_electrostriction_Dprimeij', '_electrostriction_Dprimeij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (23, '_prop_heat_capacity_C', '_heat_capacity_C', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (24, '_prop_internal_friction_Qij-1', '_internal_friction_Qij-1', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (25, '_prop_magnetic_antiferromagnetic_ordering_temperature_Neel', '_magnetic_antiferromagnetic_ordering_temperature_Neel', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (26, '_prop_magnetic_paramagnetic_critical_temperature_Neel', '_magnetic_paramagnetic_critical_temperature_Neel', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (27, '_prop_magnetic_paramagnetic_critical_temperature_Neel_transitionwidth', '_magnetic_paramagnetic_critical_temperature_Neel_transitionwidth', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (28, '_prop_optical_index_extraordinary_ne', '_optical_index_extraordinary_ne', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (29, '_prop_optical_index_ordinary_no', '_optical_index_ordinary_no', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (30, '_prop_optical_index_principal_Ni', '_optical_index_principal_Ni', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (31, '_prop_photoelastic_pij', '_photoelastic_pij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (32, '_prop_photoelastic_pijE', '_photoelastic_pijE', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (33, '_prop_piezoelectric_dij', '_piezoelectric_dij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (34, '_prop_piezoelectric_eij', '_piezoelectric_eij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (35, '_prop_piezoelectric_gij', '_piezoelectric_gij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (36, '_prop_piezoelectric_hij', '_piezoelectric_hij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (37, '_prop_piezooptic_piij', '_piezooptic_piij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (38, '_prop_residual_resistivity_ratio', '_residual_resistivity_ratio', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (39, '_prop_residual_resistivity_ratio_high_temperature', '_residual_resistivity_ratio_high_temperature', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (40, '_prop_residual_resistivity_ratio_low_temperature', '_residual_resistivity_ratio_low_temperature', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (41, '_prop_superconducting_coherence_length_ksii', '_superconducting_coherence_length_ksii', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (42, '_prop_superconducting_critical_field1_Hc1i', '_superconducting_critical_field1_Hc1i', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (43, '_prop_superconducting_critical_field2_Hc2i', '_superconducting_critical_field2_Hc2i', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (44, '_prop_superconducting_critical_temperature_mid_50', '_superconducting_critical_temperature_mid_50', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (45, '_prop_superconducting_critical_temperature_offset_10', '_superconducting_critical_temperature_offset_10', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (46, '_prop_superconducting_critical_temperature_onset', '_superconducting_critical_temperature_onset', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (47, '_prop_superconducting_critical_temperature_onset_90', '_superconducting_critical_temperature_onset_90', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (48, '_prop_superconducting_critical_temperature_thermodynamic', '_superconducting_critical_temperature_thermodynamic', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (49, '_prop_superconducting_irreversibility_field_Hirri', '_superconducting_irreversibility_field_Hirri', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (50, '_prop_superconducting_penetration_depth_lambdai', '_superconducting_penetration_depth_lambdai', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (51, '_prop_superconducting_resistivity_transition_width', '_superconducting_resistivity_transition_width', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (52, '_prop_superconducting_zero_resistivity_temperature', '_superconducting_zero_resistivity_temperature', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (53, '_prop_thermal_conductivity_kappaij', '_thermal_conductivity_kappaij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (54, '_prop_thermal_diffusivity_kappadij', '_thermal_diffusivity_kappadij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (55, '_prop_thermal_expansion_Tij', '_thermal_expansion_Tij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (56, '_prop_thermal_expansion_alphaij', '_thermal_expansion_alphaij', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (57, '_prop_thermoelastic_compliance_1storder_sij1T', '_thermoelastic_compliance_1storder_sij1T', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (58, '_prop_thermoelastic_compliance_2ndorder_sij2T', '_thermoelastic_compliance_2ndorder_sij2T', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (59, '_prop_thermoelastic_compliance_3rdorder_sij3T', '_thermoelastic_compliance_3rdorder_sij3T', 0, 'NULL', 'NULL');
INSERT INTO data_property (id, tag, description, tensor_dimensions, units, units_detail) VALUES (60, '_prop_thermoelectric_Seebeck_Seij', '_thermoelectric_Seebeck_Seij', 0, 'NULL', 'NULL');
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000001, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000001, 24);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000002, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000003, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000003, 54);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000004, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000005, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000006, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000007, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000008, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000009, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000010, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000011, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000012, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000013, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000014, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000015, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000016, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000016, 54);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000017, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000018, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000019, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000020, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000020, 54);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000021, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000022, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000023, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000024, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000025, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000026, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000027, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000028, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000029, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000030, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000031, 37);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000032, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000033, 37);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000034, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000035, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000036, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000037, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000038, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000039, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000040, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000041, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000042, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000042, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000042, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000042, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000043, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000044, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000045, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000046, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000047, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000048, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000049, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000050, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000051, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000052, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000053, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000054, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000055, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000055, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000056, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000057, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000058, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000059, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000060, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000061, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000062, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000063, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000064, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000065, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 54);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 23);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 29);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000066, 28);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 38);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 39);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 40);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000067, 41);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000068, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000069, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000070, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000071, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000072, 21);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000072, 22);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000073, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000073, 21);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000073, 22);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000074, 21);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000074, 22);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000075, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000076, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000077, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000078, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000079, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000079, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000080, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000081, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000082, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000083, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000084, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000085, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000086, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000087, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000088, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000089, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000090, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000091, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000092, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000093, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000094, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000094, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000095, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000096, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 38);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 39);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 40);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000097, 41);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000098, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000099, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000100, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000100, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000101, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000102, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000102, 41);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000102, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000103, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000104, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000105, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000106, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000107, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000108, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000109, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000110, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000111, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 47);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 45);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 48);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 51);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 42);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 49);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 41);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 50);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 38);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 39);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000112, 40);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000113, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000114, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000114, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000114, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000114, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000114, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000115, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 38);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 39);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 40);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 60);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000116, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000117, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000118, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000119, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000120, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000120, 26);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000120, 27);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000121, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000122, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000123, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000124, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000125, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000126, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000127, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000128, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000129, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000130, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000131, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000132, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000133, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000134, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000135, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000136, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000137, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000138, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000139, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000140, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000141, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000142, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000143, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000144, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000145, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000146, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000147, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000148, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000149, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000150, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000151, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000152, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000153, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000154, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000155, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000156, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000157, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000158, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000158, 29);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000158, 28);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000159, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000160, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000161, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000162, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000163, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000164, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000165, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000166, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000167, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000168, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000169, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000170, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000171, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000172, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000173, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000174, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000175, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000176, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000176, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000176, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000177, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000177, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000178, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000179, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000180, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000181, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000181, 37);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000182, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000182, 37);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000183, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000184, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000185, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000186, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000187, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000187, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000187, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000187, 55);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000188, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000188, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000188, 55);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000189, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000189, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000190, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000191, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000192, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000193, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000194, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000195, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000196, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000197, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000198, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000199, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000199, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000200, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000200, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000201, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000201, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000202, 44);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000202, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000203, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000204, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000205, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000206, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000207, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000208, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000209, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000210, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000211, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000212, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000213, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000214, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000215, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000215, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000216, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000216, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000217, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000218, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000219, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000220, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000221, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000222, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000222, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000223, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000224, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000225, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000226, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000227, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000228, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000229, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000230, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000231, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000231, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000232, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000233, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000234, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000235, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000236, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000237, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000238, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000239, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000240, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000241, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000242, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000243, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000244, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000245, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000246, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000247, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000248, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000249, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000250, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000251, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000252, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000253, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000254, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000255, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000256, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000256, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000256, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000257, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000257, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000257, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000258, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000258, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000258, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000259, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000259, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000259, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000260, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000260, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000260, 25);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000261, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000262, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000263, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000264, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000265, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000266, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000267, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000268, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000269, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000270, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000271, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000272, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000273, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000274, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000274, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000274, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000274, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000275, 46);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000275, 52);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000275, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000275, 43);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000276, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000277, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 16);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 15);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000278, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 16);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 15);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000279, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000280, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000280, 37);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000281, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000281, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000282, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000283, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000284, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000285, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000286, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000287, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000288, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000289, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000290, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000291, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000292, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000293, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000294, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000295, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 57);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 58);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000296, 59);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000297, 13);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000298, 13);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000299, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000299, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000300, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000301, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000302, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000303, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000304, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000305, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 19);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 20);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 32);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000306, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000307, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000307, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000307, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000307, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 1);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000308, 57);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000309, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000310, 7);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000310, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000311, 6);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000312, 23);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000312, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000312, 54);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000312, 56);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000313, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000314, 14);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000314, 17);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000314, 60);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000315, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000316, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000317, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000318, 53);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000319, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000320, 10);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000320, 30);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000320, 31);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 4);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 5);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 2);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 3);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 8);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 9);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 12);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 11);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 18);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 33);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 34);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 35);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000321, 36);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000322, 13);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000323, 13);
INSERT INTO data_datafile_property (datafile_id, property_id) VALUES (1000324, 25);
UPDATE data_property SET name = ' prop dielectric permittivity relative epsrij'WHERE tag = '_prop_dielectric_permittivity_relative_epsrij';
UPDATE data_property SET units = '1'WHERE tag = '_prop_dielectric_permittivity_relative_epsrij';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_dielectric_permittivity_relative_epsrij';
UPDATE data_property SET name = ' prop dielectric permittivity relative epsrijS'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijS';
UPDATE data_property SET units = '1'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijS';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijS';
UPDATE data_property SET name = ' prop dielectric permittivity relative epsrijT'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijT';
UPDATE data_property SET units = '1'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijT';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_dielectric_permittivity_relative_epsrijT';
UPDATE data_property SET name = ' prop dielectric stiffness relative betrijS'WHERE tag = '_prop_dielectric_stiffness_relative_betrijS';
UPDATE data_property SET units = '10^-4'WHERE tag = '_prop_dielectric_stiffness_relative_betrijS';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_dielectric_stiffness_relative_betrijS';
UPDATE data_property SET name = ' prop dielectric stiffness relative betrijT'WHERE tag = '_prop_dielectric_stiffness_relative_betrijT';
UPDATE data_property SET units = '10^-4'WHERE tag = '_prop_dielectric_stiffness_relative_betrijT';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_dielectric_stiffness_relative_betrijT';
UPDATE data_property SET name = ' prop elastic TOEC stiffness cijk'WHERE tag = '_prop_elastic_TOEC_stiffness_cijk';
UPDATE data_property SET units = 'GPa'WHERE tag = '_prop_elastic_TOEC_stiffness_cijk';
UPDATE data_property SET units_detail = 'giga pascal'WHERE tag = '_prop_elastic_TOEC_stiffness_cijk';
UPDATE data_property SET name = ' prop elastic compliance sij'WHERE tag = '_prop_elastic_compliance_sij';
UPDATE data_property SET units = '10^-12.m^2.Pa^-1'WHERE tag = '_prop_elastic_compliance_sij';
UPDATE data_property SET units_detail = 'metre square over tera pascal'WHERE tag = '_prop_elastic_compliance_sij';
UPDATE data_property SET name = ' prop elastic compliance sijD'WHERE tag = '_prop_elastic_compliance_sijD';
UPDATE data_property SET units = '10^-12.m^2.Pa^-1'WHERE tag = '_prop_elastic_compliance_sijD';
UPDATE data_property SET units_detail = 'metre square over tera pascal'WHERE tag = '_prop_elastic_compliance_sijD';
UPDATE data_property SET name = ' prop elastic compliance sijE'WHERE tag = '_prop_elastic_compliance_sijE';
UPDATE data_property SET units = '10^-12.m^2.Pa^-1'WHERE tag = '_prop_elastic_compliance_sijE';
UPDATE data_property SET units_detail = 'metre square over tera pascal'WHERE tag = '_prop_elastic_compliance_sijE';
UPDATE data_property SET name = ' prop elastic stiffness cij'WHERE tag = '_prop_elastic_stiffness_cij';
UPDATE data_property SET units = 'GPa'WHERE tag = '_prop_elastic_stiffness_cij';
UPDATE data_property SET units_detail = 'giga Pascal'WHERE tag = '_prop_elastic_stiffness_cij';
UPDATE data_property SET name = ' prop elastic stiffness cijD'WHERE tag = '_prop_elastic_stiffness_cijD';
UPDATE data_property SET units = 'GPa'WHERE tag = '_prop_elastic_stiffness_cijD';
UPDATE data_property SET units_detail = 'giga Pascal'WHERE tag = '_prop_elastic_stiffness_cijD';
UPDATE data_property SET name = ' prop elastic stiffness cijE'WHERE tag = '_prop_elastic_stiffness_cijE';
UPDATE data_property SET units = 'GPa'WHERE tag = '_prop_elastic_stiffness_cijE';
UPDATE data_property SET units_detail = 'giga Pascal'WHERE tag = '_prop_elastic_stiffness_cijE';
UPDATE data_property SET name = ' prop elastic stiffness cijS'WHERE tag = '_prop_elastic_stiffness_cijS';
UPDATE data_property SET units = 'GPa'WHERE tag = '_prop_elastic_stiffness_cijS';
UPDATE data_property SET units_detail = 'giga Pascal'WHERE tag = '_prop_elastic_stiffness_cijS';
UPDATE data_property SET name = ' prop electric charge carrier concentration n'WHERE tag = '_prop_electric_charge_carrier_concentration_n';
UPDATE data_property SET units = '10^19 cm-3'WHERE tag = '_prop_electric_charge_carrier_concentration_n';
UPDATE data_property SET units_detail = 'atoms per cubic centimetre'WHERE tag = '_prop_electric_charge_carrier_concentration_n';
UPDATE data_property SET name = ' prop electric coercive field Eci'WHERE tag = '_prop_electric_coercive_field_Eci';
UPDATE data_property SET units = 'kV.cm^-1'WHERE tag = '_prop_electric_coercive_field_Eci';
UPDATE data_property SET units_detail = 'kilovolts per centimetre'WHERE tag = '_prop_electric_coercive_field_Eci';
UPDATE data_property SET name = ' prop electric remnant polarisation Pri'WHERE tag = '_prop_electric_remnant_polarisation_Pri';
UPDATE data_property SET units = '10^-6 Ohm.cm^-2'WHERE tag = '_prop_electric_remnant_polarisation_Pri';
UPDATE data_property SET units_detail = 'micro Ohm per square centimetre'WHERE tag = '_prop_electric_remnant_polarisation_Pri';
UPDATE data_property SET name = ' prop electric resistivity rhoeij'WHERE tag = '_prop_electric_resistivity_rhoeij';
UPDATE data_property SET units = '10^-6 Ohm.cm'WHERE tag = '_prop_electric_resistivity_rhoeij';
UPDATE data_property SET units_detail = 'micro Ohm per centimetre'WHERE tag = '_prop_electric_resistivity_rhoeij';
UPDATE data_property SET name = ' prop electromechanical coupling kij'WHERE tag = '_prop_electromechanical_coupling_kij';
UPDATE data_property SET units = '1'WHERE tag = '_prop_electromechanical_coupling_kij';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_electromechanical_coupling_kij';
UPDATE data_property SET name = ' prop electrooptic rijkS'WHERE tag = '_prop_electrooptic_rijkS';
UPDATE data_property SET units = '10^-12.m.V'WHERE tag = '_prop_electrooptic_rijkS';
UPDATE data_property SET units_detail = 'parts per trillion metres volts'WHERE tag = '_prop_electrooptic_rijkS';
UPDATE data_property SET name = ' prop electrooptic rijkT'WHERE tag = '_prop_electrooptic_rijkT';
UPDATE data_property SET units = '10^-12.m.V'WHERE tag = '_prop_electrooptic_rijkT';
UPDATE data_property SET units_detail = 'parts per trillion metres volts'WHERE tag = '_prop_electrooptic_rijkT';
UPDATE data_property SET name = ' prop electrostriction Dij'WHERE tag = '_prop_electrostriction_Dij';
UPDATE data_property SET units = '10^-20.m^2.V^-2 and m^4.C^-2'WHERE tag = '_prop_electrostriction_Dij';
UPDATE data_property SET units_detail = '10^-20.m^2V^-2 and m^4.C^-2'WHERE tag = '_prop_electrostriction_Dij';
UPDATE data_property SET name = ' prop electrostriction Dprimeij'WHERE tag = '_prop_electrostriction_Dprimeij';
UPDATE data_property SET units = '10^-20.m^2.V^-2 and m^4.C^-2'WHERE tag = '_prop_electrostriction_Dprimeij';
UPDATE data_property SET units_detail = '10^-20.m^2V^-2 and m^4.C^-2'WHERE tag = '_prop_electrostriction_Dprimeij';
UPDATE data_property SET name = ' prop heat capacity C'WHERE tag = '_prop_heat_capacity_C';
UPDATE data_property SET units = 'Jg^-1K^-1'WHERE tag = '_prop_heat_capacity_C';
UPDATE data_property SET units_detail = 'joules per gram per kelvin'WHERE tag = '_prop_heat_capacity_C';
UPDATE data_property SET name = ' prop internal friction Qij-1'WHERE tag = '_prop_internal_friction_Qij-1';
UPDATE data_property SET units = '10^-4'WHERE tag = '_prop_internal_friction_Qij-1';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_internal_friction_Qij-1';
UPDATE data_property SET name = ' prop magnetic antiferromagnetic ordering temperature Neel'WHERE tag = '_prop_magnetic_antiferromagnetic_ordering_temperature_Neel';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_magnetic_antiferromagnetic_ordering_temperature_Neel';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_magnetic_antiferromagnetic_ordering_temperature_Neel';
UPDATE data_property SET name = ' prop magnetic paramagnetic critical temperature Neel'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel';
UPDATE data_property SET name = ' prop magnetic paramagnetic critical temperature Neel transitionwidth'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel_transitionwidth';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel_transitionwidth';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_magnetic_paramagnetic_critical_temperature_Neel_transitionwidth';
UPDATE data_property SET name = ' prop optical index extraordinary ne'WHERE tag = '_prop_optical_index_extraordinary_ne';
UPDATE data_property SET units = '1'WHERE tag = '_prop_optical_index_extraordinary_ne';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_optical_index_extraordinary_ne';
UPDATE data_property SET name = ' prop optical index ordinary no'WHERE tag = '_prop_optical_index_ordinary_no';
UPDATE data_property SET units = '1'WHERE tag = '_prop_optical_index_ordinary_no';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_optical_index_ordinary_no';
UPDATE data_property SET name = ' prop optical index principal Ni'WHERE tag = '_prop_optical_index_principal_Ni';
UPDATE data_property SET units = '1'WHERE tag = '_prop_optical_index_principal_Ni';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_optical_index_principal_Ni';
UPDATE data_property SET name = ' prop photoelastic pij'WHERE tag = '_prop_photoelastic_pij';
UPDATE data_property SET units = '1'WHERE tag = '_prop_photoelastic_pij';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_photoelastic_pij';
UPDATE data_property SET name = ' prop photoelastic pijE'WHERE tag = '_prop_photoelastic_pijE';
UPDATE data_property SET units = '1'WHERE tag = '_prop_photoelastic_pijE';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_photoelastic_pijE';
UPDATE data_property SET name = ' prop piezoelectric dij'WHERE tag = '_prop_piezoelectric_dij';
UPDATE data_property SET units = 'm.V^-1'WHERE tag = '_prop_piezoelectric_dij';
UPDATE data_property SET units_detail = 'meter per volt'WHERE tag = '_prop_piezoelectric_dij';
UPDATE data_property SET name = ' prop piezoelectric eij'WHERE tag = '_prop_piezoelectric_eij';
UPDATE data_property SET units = 'C.N^-1'WHERE tag = '_prop_piezoelectric_eij';
UPDATE data_property SET units_detail = 'coulomb per newton'WHERE tag = '_prop_piezoelectric_eij';
UPDATE data_property SET name = ' prop piezoelectric gij'WHERE tag = '_prop_piezoelectric_gij';
UPDATE data_property SET units = 'C.m^-2'WHERE tag = '_prop_piezoelectric_gij';
UPDATE data_property SET units_detail = 'coulomb oer square metre'WHERE tag = '_prop_piezoelectric_gij';
UPDATE data_property SET name = ' prop piezoelectric hij'WHERE tag = '_prop_piezoelectric_hij';
UPDATE data_property SET units = 'V.m.N^-1'WHERE tag = '_prop_piezoelectric_hij';
UPDATE data_property SET units_detail = 'volt metre per newton'WHERE tag = '_prop_piezoelectric_hij';
UPDATE data_property SET name = ' prop piezooptic piij'WHERE tag = '_prop_piezooptic_piij';
UPDATE data_property SET units = 'MPa^-1'WHERE tag = '_prop_piezooptic_piij';
UPDATE data_property SET units_detail = 'one over mega Pascal'WHERE tag = '_prop_piezooptic_piij';
UPDATE data_property SET name = ' prop residual resistivity ratio'WHERE tag = '_prop_residual_resistivity_ratio';
UPDATE data_property SET units = '1'WHERE tag = '_prop_residual_resistivity_ratio';
UPDATE data_property SET units_detail = 'pure number'WHERE tag = '_prop_residual_resistivity_ratio';
UPDATE data_property SET name = ' prop residual resistivity ratio high temperature'WHERE tag = '_prop_residual_resistivity_ratio_high_temperature';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_residual_resistivity_ratio_high_temperature';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_residual_resistivity_ratio_high_temperature';
UPDATE data_property SET name = ' prop residual resistivity ratio low temperature'WHERE tag = '_prop_residual_resistivity_ratio_low_temperature';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_residual_resistivity_ratio_low_temperature';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_residual_resistivity_ratio_low_temperature';
UPDATE data_property SET name = ' prop superconducting coherence length ksii'WHERE tag = '_prop_superconducting_coherence_length_ksii';
UPDATE data_property SET units = 'nm'WHERE tag = '_prop_superconducting_coherence_length_ksii';
UPDATE data_property SET units_detail = 'nanometre'WHERE tag = '_prop_superconducting_coherence_length_ksii';
UPDATE data_property SET name = ' prop superconducting critical field1 Hc1i'WHERE tag = '_prop_superconducting_critical_field1_Hc1i';
UPDATE data_property SET units = 'T'WHERE tag = '_prop_superconducting_critical_field1_Hc1i';
UPDATE data_property SET units_detail = 'tesla'WHERE tag = '_prop_superconducting_critical_field1_Hc1i';
UPDATE data_property SET name = ' prop superconducting critical field2 Hc2i'WHERE tag = '_prop_superconducting_critical_field2_Hc2i';
UPDATE data_property SET units = 'T'WHERE tag = '_prop_superconducting_critical_field2_Hc2i';
UPDATE data_property SET units_detail = 'tesla'WHERE tag = '_prop_superconducting_critical_field2_Hc2i';
UPDATE data_property SET name = ' prop superconducting critical temperature mid 50'WHERE tag = '_prop_superconducting_critical_temperature_mid_50';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_critical_temperature_mid_50';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_critical_temperature_mid_50';
UPDATE data_property SET name = ' prop superconducting critical temperature offset 10'WHERE tag = '_prop_superconducting_critical_temperature_offset_10';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_critical_temperature_offset_10';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_critical_temperature_offset_10';
UPDATE data_property SET name = ' prop superconducting critical temperature onset'WHERE tag = '_prop_superconducting_critical_temperature_onset';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_critical_temperature_onset';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_critical_temperature_onset';
UPDATE data_property SET name = ' prop superconducting critical temperature onset 90'WHERE tag = '_prop_superconducting_critical_temperature_onset_90';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_critical_temperature_onset_90';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_critical_temperature_onset_90';
UPDATE data_property SET name = ' prop superconducting critical temperature thermodynamic'WHERE tag = '_prop_superconducting_critical_temperature_thermodynamic';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_critical_temperature_thermodynamic';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_critical_temperature_thermodynamic';
UPDATE data_property SET name = ' prop superconducting irreversibility field Hirri'WHERE tag = '_prop_superconducting_irreversibility_field_Hirri';
UPDATE data_property SET units = 'T'WHERE tag = '_prop_superconducting_irreversibility_field_Hirri';
UPDATE data_property SET units_detail = 'tesla'WHERE tag = '_prop_superconducting_irreversibility_field_Hirri';
UPDATE data_property SET name = ' prop superconducting penetration depth lambdai'WHERE tag = '_prop_superconducting_penetration_depth_lambdai';
UPDATE data_property SET units = 'nm'WHERE tag = '_prop_superconducting_penetration_depth_lambdai';
UPDATE data_property SET units_detail = 'nanometre'WHERE tag = '_prop_superconducting_penetration_depth_lambdai';
UPDATE data_property SET name = ' prop superconducting resistivity transition width'WHERE tag = '_prop_superconducting_resistivity_transition_width';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_resistivity_transition_width';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_resistivity_transition_width';
UPDATE data_property SET name = ' prop superconducting zero resistivity temperature'WHERE tag = '_prop_superconducting_zero_resistivity_temperature';
UPDATE data_property SET units = 'K'WHERE tag = '_prop_superconducting_zero_resistivity_temperature';
UPDATE data_property SET units_detail = 'kelvin'WHERE tag = '_prop_superconducting_zero_resistivity_temperature';
UPDATE data_property SET name = ' prop thermal conductivity kappaij'WHERE tag = '_prop_thermal_conductivity_kappaij';
UPDATE data_property SET units = 'W.K^-1.m^-1'WHERE tag = '_prop_thermal_conductivity_kappaij';
UPDATE data_property SET units_detail = 'watt per kelvin per metre'WHERE tag = '_prop_thermal_conductivity_kappaij';
UPDATE data_property SET name = ' prop thermal diffusivity kappadij'WHERE tag = '_prop_thermal_diffusivity_kappadij';
UPDATE data_property SET units = 'm^2.s^-1'WHERE tag = '_prop_thermal_diffusivity_kappadij';
UPDATE data_property SET units_detail = 'metre squared per second'WHERE tag = '_prop_thermal_diffusivity_kappadij';
UPDATE data_property SET name = ' prop thermal expansion Tij'WHERE tag = '_prop_thermal_expansion_Tij';
UPDATE data_property SET units = 'MPa.K^-1'WHERE tag = '_prop_thermal_expansion_Tij';
UPDATE data_property SET units_detail = 'megapascal per kelvin'WHERE tag = '_prop_thermal_expansion_Tij';
UPDATE data_property SET name = ' prop thermal expansion alphaij'WHERE tag = '_prop_thermal_expansion_alphaij';
UPDATE data_property SET units = '10^-6.K^-1'WHERE tag = '_prop_thermal_expansion_alphaij';
UPDATE data_property SET units_detail = 'parts per million per kelvin'WHERE tag = '_prop_thermal_expansion_alphaij';
UPDATE data_property SET name = ' prop thermoelastic compliance 1storder sij1T'WHERE tag = '_prop_thermoelastic_compliance_1storder_sij1T';
UPDATE data_property SET units = '10^-6.K^-1'WHERE tag = '_prop_thermoelastic_compliance_1storder_sij1T';
UPDATE data_property SET units_detail = 'parts per million per kelvin'WHERE tag = '_prop_thermoelastic_compliance_1storder_sij1T';
UPDATE data_property SET name = ' prop thermoelastic compliance 2ndorder sij2T'WHERE tag = '_prop_thermoelastic_compliance_2ndorder_sij2T';
UPDATE data_property SET units = '10^-9.K^-1'WHERE tag = '_prop_thermoelastic_compliance_2ndorder_sij2T';
UPDATE data_property SET units_detail = 'parts per million per kelvin'WHERE tag = '_prop_thermoelastic_compliance_2ndorder_sij2T';
UPDATE data_property SET name = ' prop thermoelastic compliance 3rdorder sij3T'WHERE tag = '_prop_thermoelastic_compliance_3rdorder_sij3T';
UPDATE data_property SET units = '10^-12.K^-1'WHERE tag = '_prop_thermoelastic_compliance_3rdorder_sij3T';
UPDATE data_property SET units_detail = 'parts per million per kelvin'WHERE tag = '_prop_thermoelastic_compliance_3rdorder_sij3T';
UPDATE data_property SET name = ' prop thermoelectric Seebeck Seij'WHERE tag = '_prop_thermoelectric_Seebeck_Seij';
UPDATE data_property SET units = '10^-6.V.K^-1'WHERE tag = '_prop_thermoelectric_Seebeck_Seij';
UPDATE data_property SET units_detail = 'parts per million volts per kelvin'WHERE tag = '_prop_thermoelectric_Seebeck_Seij';
COMMIT;
